package org.maia.amstrad.load.basic.staged.file;

public interface FileCommandDelays {

	long DELAYMILLIS_CHAIN_MERGE = 2000L;

	long DELAYMILLIS_CHAIN_RUN = 2000L;

	long DELAYMILLIS_BINARY_LOAD_NEW_BLOCK = 500L;

	long DELAYMILLIS_BINARY_LOAD_DWORD = 8L;

	long DELAYMILLIS_BINARY_LOAD = 2000L;

	long DELAYMILLIS_BINARY_SAVE = 2000L;

	long DELAYMILLIS_OPENOUT = 2000L;

	long DELAYMILLIS_PRINTSTREAM = 0L;

	long DELAYMILLIS_CLOSEOUT = 0L;

	long DELAYMILLIS_OPENIN = 2000L;

	long DELAYMILLIS_INPUTSTREAM = 0L;

	long DELAYMILLIS_CLOSEIN = 0L;

}