package org.maia.amstrad.program;

public interface AmstradProgramMetaDataConstants {

	String AMD_INCLUDE = "INCLUDE";

	String AMD_TYPE = "TYPE";

	String AMD_TYPE_LOCOMOTIVE_BASIC_PROGRAM = "LOCOMOTIVE BASIC PROGRAM";

	String AMD_NAME = "NAME";

	String AMD_AUTHOR = "AUTHOR";

	String AMD_YEAR = "YEAR";

	String AMD_TAPE = "TAPE";

	String AMD_BLOCKS = "BLOCKS";

	String AMD_MONITOR = "MONITOR";

	String AMD_DESCRIPTION = "DESCRIPTION";

	String AMD_AUTHORING = "AUTHORING";

	String AMD_CONTROLS_PREFIX = "CONTROLS";

	String AMD_CONTROLS_SUFFIX_HEADING = "HEADING";

	String AMD_CONTROLS_SUFFIX_KEY = "KEY";

	String AMD_CONTROLS_SUFFIX_DESCRIPTION = "DESCRIPTION";

	String AMD_IMAGES_PREFIX = "IMAGES";

	String AMD_IMAGES_SUFFIX_FILEREF = "FILEREF";

	String AMD_IMAGES_SUFFIX_CAPTION = "CAPTION";

	String AMD_COVER_IMAGE = "COVERIMAGE";

	String AMD_COVER_IMAGE_BADGE_ID = "COVERIMAGE-BADGE-ID";
	
	String AMD_FILEREFS_PREFIX = "FILEREFS";

	String AMD_FILEREFS_DESCRIBED_BY = "DESCRIBED BY";

	String AMD_FLAGS = "FLAGS";

	String AMD_FLAG_HIDE = "HIDE";

	String AMD_FLAG_FEATURED = "FEATURED";

	String AMD_FLAG_NOLAUNCH = "NO-LAUNCH";

	String AMD_FLAG_NOSTAGE = "NO-STAGE";

	String AMD_FLAG_NODIRECTJOY = "NO-DIRECTJOY";

}